sudo: required
dist: xenial
language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libedit-dev libedit2 bats

jdk:
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - CC=clang
  - CC=gcc

script:
  - echo "Running with LANG=$LANG, bats $(bats --version)"
  - mvn clean site install
  - make clean bats T_LIBS="JavaEditline JavaReadline JavaGetline" BROKEN_EDITLINE_HISTORY=1 CC=$CC

